### ISSUE TITLE
'ffmpeg' is not recognized as an internal command

### ISSUE THREAD

**Issue by matoqwerty** [zackmawaldi/YouTube-shorts-generator#11]
Hello, moviepy and ffmpeg both package are installed and i dont find the part where are the call function "ffmpeg" anywhere, somebody can help me please?

```
(env) PS D:\Users\Thomas\dev\YouTube-shorts-generator> python3 main.py     
Logging into Reddit...
Log in success! Retrieving post info...
I wasn’t convinced until now…. we are definitely in a simulation. Today I randomly swam past my Doppelseäner at the Flamingo pool in Vegas.
Barksy
But I swear it was here!
But I swear it was here!  funny  zhaneq14
https://v.redd.it/wt4eebysoti91

Coach hears his translator for the first time
Coach hears his translator for the first time  funny  S-_Lifts
https://v.redd.it/gwmdwg5lnbi91

Japan needs YOU 🍺
Leslie Nielsen in Detroit: Become Human
Leslie Nielsen in Detroit: Become Human  funny  Ishnuporah
https://v.redd.it/7q1p1n60zgi91

There's marijuana in there!
There's marijuana in there!  funny  ecky--ptang-zooboing
https://v.redd.it/9ejd5ehjbii91

Inflation hits the lemonade stands
Inflation hits the lemonade stands  funny  tefunka
https://v.redd.it/wfqx1ehmowh91

Whilst on holiday, my sister asked for an update picture of her two cats. This is what she got...
he on another level
The hotel I’m staying in keeps adding a new roll of toilet paper every day 
even though I’m not using any.
Did I get it in?
Did I get it in?  funny  lilmammamia
https://v.redd.it/eqkmt1ozm4j91

I pity the tool
The best disabled plate I’ve ever seen
As a Midwesterner, these critters are a TREAT when visiting Florida.       
As a Midwesterner, these critters are a TREAT when visiting Florida.  funny  Everythingsphyne
https://v.redd.it/zcwf3quvnyh91

First day back to school, and what do I see?
I am utterly surprised that this hasn't been vandalized already.
Handegg
My brother gave me the best birthday card
Someone sent me this muppet pic to insult me and it just cracked me up instead
the grandma
Releasing my farm cat Pork Chop after a vet visit 😂🚀
Releasing my farm cat Pork Chop after a vet visit 😂🚀  funny  blackflameandcocaine
https://v.redd.it/gz6n893w43j91

Husband knows how to trigger wife
Husband knows how to trigger wife  funny  somek_pamak
https://v.redd.it/9a2xkrn39ii91

Dance like nobody's watching.
Dance like nobody's watching.  funny  Tricky-Awareness7465
https://v.redd.it/a97b16zspti91

Party..
Party..  funny  Sad_Friendship4043
https://v.redd.it/au6ep6yv08j91

[('https://v.redd.it/wt4eebysoti91', 'But I swear it was here!', 'zhaneq14'), ('https://v.redd.it/gwmdwg5lnbi91', 'Coach hears his translator for the 
first time', 'S-_Lifts'), ('https://v.redd.it/7q1p1n60zgi91', 'Leslie Nielsen in Detroit: Become Human', 'Ishnuporah'), ('https://v.redd.it/9ejd5ehjbii91', "There's marijuana in there!", 'ecky--ptang-zooboing'), ('https://v.redd.it/wfqx1ehmowh91', 'Inflation hits the lemonade stands', 'tefunka'), ('https://v.redd.it/eqkmt1ozm4j91', 'Did I get it in?', 'lilmammamia'), ('https://v.redd.it/zcwf3quvnyh91', 'As a Midwesterner, these critters are a TREAT when visiting Florida.', 'Everythingsphyne'), ('https://v.redd.it/gz6n893w43j91', 'Releasing my farm cat Pork Chop after a vet visit 😂🚀', 'blackflameandcocaine'), ('https://v.redd.it/9a2xkrn39ii91', 'Husband knows how to trigger wife', 'somek_pamak'), ('https://v.redd.it/a97b16zspti91', "Dance 
like nobody's watching.", 'Tricky-Awareness7465'), ('https://v.redd.it/au6ep6yv08j91', 'Party..', 'Sad_Friendship4043')]
>> Connecting...
>> Scraping...
>> Connecting...
>> Scraping...
>> Downloading and Re-encoding...
>> Video:
>>>> [██████████████████████████████████████████████████] [2.60/2.60 MB]
'ffmpeg' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Traceback (most recent call last):
  File "D:\Users\Thomas\dev\YouTube-shorts-generator\main.py", line 32, in 
<module>
    rs.download_vid(vid_list[x][0], directory)
  File "D:\Users\Thomas\dev\YouTube-shorts-generator\reddit_scraper.py", line 11, in download_vid
    download.download()
  File "C:\Users\31smo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redvid\redvid.py", line 254, in download
    self.get_and_mux()
  File "C:\Users\31smo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redvid\redvid.py", line 149, in get_and_mux
    os.rename(self.temp + 'av.mp4', self.file_name)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'temp_clips/\\redvid_temp\\yvyWOdRIBNuTbKSNwxxLJk8PGvwvugiWBOfT6cLqZDA\\av.mp4' -> 'temp_clips/\\wt4eebysoti91-DASH_480.mp4'
```

**Comment by zackmawaldi** [comment]
Check if this video helps.
https://www.youtube.com/watch?v=wXDsMKJyK9c
