### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by underscorelunar** [zackmawaldi/YouTube-shorts-generator#12]
gettinth this error
 File "C:\Users\evand\Desktop\YouTube-shorts-generator-main\YouTube-shorts-generator-main\main.py", line 19, in <module>
    vid_list = rs.reddit_scraper(subreddit)
  File "C:\Users\evand\Desktop\YouTube-shorts-generator-main\YouTube-shorts-generator-main\reddit_scraper.py", line 18, in reddit_scraper
    red = praw.Reddit(client_id=config.reddit_login['**************'],
KeyError: '***************'
![21d0d67207267d9f11327ffe685de4a2 (1)](https://user-images.githubusercontent.com/88303483/186238706-e4ef889c-cc7c-454d-9ceb-abd8bd534341.png)

**Comment by matoqwerty** [comment]
All login informations nees to be completed inside config.py


Import config
Password=config.reddit_login['client_id']
