### ISSUE TITLE
'bool' object is not callable

### ISSUE THREAD

**Issue by apoorvpandey0** [zackmawaldi/YouTube-shorts-generator#19]
```
main.py
Traceback (most recent call last):
  File "c:/Users/apoor/Documents/YouTube-shorts-generator/main.py", line 38, in <module>
    r.render(directory, "main_clip.mp4", "output.mp4", config.video['dimensions'])
  File "c:\Users\apoor\Documents\YouTube-shorts-generator\render.py", line 34, in render
    bg = bg.fl_image(blur)
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\video\VideoClip.py", line 490, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-61>", line 2, in set_make_frame
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\video\VideoClip.py", line 644, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Users\apoor\Documents\YouTube-shorts-generator\env\lib\site-packages\moviepy\video\VideoClip.py", line 490, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
TypeError: 'bool' object is not callable
```

**Comment by apoorvpandey0** [comment]
This is happening because blur is a variable name as well as a function name, changing either one works!
