### ISSUE TITLE
UnboundLocalError: local variable 'vid' referenced before assignment

### ISSUE THREAD

**Issue by trimpta** [zackmawaldi/YouTube-shorts-generator#37]
Heres the output, i couldnt figure it out

```
(shorts-gen) D:\YouTube-shorts-generator-main>python main.py
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 1:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 2:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 3:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 4:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 5:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 6:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 7:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 8:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 9:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Error occured on 10:
 Traceback (most recent call last):
  File "D:\YouTube-shorts-generator-main\main.py", line 68, in <module>
    success = main()
  File "D:\YouTube-shorts-generator-main\main.py", line 36, in main
    if not vid:
UnboundLocalError: local variable 'vid' referenced before assignment

Retrying...

(shorts-gen) D:\YouTube-shorts-generator-main>

```

**Comment by IcedCoffeeDrinker** [comment]
I have the same issue. It only occurs when I change the subreddit though.
