### ISSUE TITLE
After logging into reddit i get these errors, what do i do?

### ISSUE THREAD

**Issue by Al7z** [zackmawaldi/YouTube-shorts-generator#9]
C:\Users\alecv\Desktop\YouTube-shorts-generator-main>main.py
Logging into Reddit...
Log in success! Retrieving post info...
Traceback (most recent call last):
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\requestor.py", line 58, in request
    return self._http.request(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 1043, in check_header_validity
    _validate_header_part(value, "value", HEADER_VALIDATORS[type(value)][1])
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 1048, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' PRAW/7.6.0 prawcore/2.3.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alecv\Desktop\YouTube-shorts-generator-main\main.py", line 19, in <module>
    vid_list = rs.reddit_scraper(subreddit)
  File "C:\Users\alecv\Desktop\YouTube-shorts-generator-main\reddit_scraper.py", line 30, in reddit_scraper
    for i in sub:
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 314, in refresh
    self._request_token(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 30, in _post
    response = self._requestor.request(
  File "C:\Users\alecv\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\requestor.py", line 62, in request
    raise RequestException(exc, args, kwargs)
prawcore.exceptions.RequestException: error with request Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' PRAW/7.6.0 prawcore/2.3.0'

**Comment by zackmawaldi** [comment]
Hmm... very weird. I have no clue and googling doesn't help. Try mentioning this issue to PRAW GitHub page here:
https://github.com/praw-dev/praw

I'd send them full error print out, as is. Good luck!
